# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Namig Abbasov'
    description: 'Professional website of Namig Abbasov, showcasing research, publications, teaching, and projects in AI and data science.'
    twitter: 'namigaabbasov'
    icon: favicon_v2.png
    same_as:
      - "https://scholar.google.com/citations?user=o6I7ydsAAAAJ&hl=en"
      - "https://orcid.org/my-orcid?orcid=0000-0002-5416-1294"
      - "https://www.linkedin.com/in/namigabbasov/"
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: '9GqhBcto0_K0rR3UYAbtNWBMHPwOXgzD3Wi6_GppzKI'
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Namig Abbasov"

# Site footer
footer:
  copyright:
    notice: '© {year} Namig Abbasov. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
